name: Build Diesel Cache
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 1

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3

      # 2. Cache Rust toolchain
      - name: Cache Rust toolchain
        uses: actions/cache@v3
        with:
          path: ~/.rustup
          key: rust-toolchain-1.90.0
          restore-keys: rust-toolchain-

      # 3. Install Rust toolchain
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.90.0
          profile: minimal
          override: true

      # 4. Cache Cargo dependencies
      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-deps-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-deps-

      # 5. Cache target directory (for incremental builds)
      - name: Cache target directory
        uses: actions/cache@v3
        with:
          path: target
          key: diesel-target-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/src/**') }}
          restore-keys: |
            diesel-target-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-
            diesel-target-${{ runner.os }}-
      
      # 6. Build Diesel only
      - name: Build Diesel
        run: |
          echo "Building Diesel with incremental compilation..."
          cargo build -p diesel -j 2
          echo "Build complete."
      
      # 7. Upload entire target directory
      - name: Upload target directory
        uses: actions/upload-artifact@v4
        with:
          name: diesel-target-directory
          path: target/
          retention-days: 30
          compression-level: 6

      # 8. Show build statistics
      - name: Show build stats
        run: |
          echo "=== Target directory size ==="
          du -sh target/
          echo "=== Incremental compilation artifacts ==="
          du -sh target/debug/incremental/ 2>/dev/null || echo "No incremental artifacts found"